version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tcp-processor-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: tcp-processor-rabbitmq
    ports:
      - "5672:5672"    # AMQP port (for application connections)
      - "15672:15672"  # Management UI port (for web interface)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  redis_data:
  rabbitmq_data: